### ISSUE TITLE
[Bug] KeyError: 'cols' when compiling q6_max:default

### ISSUE THREAD

**Issue by Jerakin** [Keychron/qmk_firmware#343]
### Describe the Bug
Using qmk msys I get a callstack when trying to compile

I want to use iso, but ansi gives the same error.

Normal q6 gives no errors.

```

$ qmk compile -kb keychron/q6_max/iso_encoder -km default

☒ Not including data from file: keyboards/keychron/q6_max/info.json
☒       rgb_matrix.driver: 'snled27351_spi' is not one of ['aw20216s', 'custom', 'is31fl3218', 'is31fl3236', 'is31fl3729', 'is31fl3731', 'is31fl3733', 'is31fl3736', 'is31fl3737', 'is31fl3741', 'is31fl3742a', 'is31fl3743a', 'is31fl3745', 'is31fl3746a', 'snled27351', 'ws2812']
☒ 'cols'
Traceback (most recent call last):
  File "D:/QMK_MSYS/mingw64/lib/python3.12/site-packages/milc/milc.py", line 606, in __call__
    return self.__call__()
           ^^^^^^^^^^^^^^^
  File "D:/QMK_MSYS/mingw64/lib/python3.12/site-packages/milc/milc.py", line 611, in __call__
    return self._subcommand(self)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "H:/projects/repositories/qmk_firmware/lib/python/qmk/cli/generate/rules_mk.py", line 65, in generate_rules_mk
    kb_info_json = dotty(info_json(cli.args.keyboard))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:/projects/repositories/qmk_firmware/lib/python/qmk/info.py", line 258, in info_json
    info_data = _extract_led_config(info_data, str(keyboard))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:/projects/repositories/qmk_firmware/lib/python/qmk/info.py", line 776, in _extract_led_config
    cols = info_data['matrix_size']['cols']
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'cols'
```

### Keyboard Used
Q6 Max, ISO

### Operating System

Windows

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by Jerakin** [comment]
Seems to be cause of out dated json files. By throwing things around a bit and renaming the `iso_encoder/info.json` to `keyboard.json` I got passed that error.

However I now get this error instead

```
☒ Not including data from file: keyboards/keychron/q6_max/info.json
☒       rgb_matrix.driver: 'snled27351_spi' is not one of ['aw20216s', 'custom', 'is31fl3218', 'is31fl3236', 'is31fl3729', 'is31fl3731', 'is31fl3733', 'is31fl3736', 'is31fl3737', 'is31fl3741', 'is31fl3742a', 'is31fl3743a', 'is31fl3745', 'is31fl3746a', 'snled27351', 'ws2812']
```

**Comment by Jerakin** [comment]
Oops, my repositories were mixed up. Tried to build it with the upstreams and not the fork.
